# Generated by Django 4.1 on 2022-08-23 17:17

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_draft_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                validators=[users.models.Profile.validate_image],
            ),
        ),
    ]
