version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./draft_fifa/:/usr/src/draft_fifa/
    ports:
      - 8000:8000
  db:
    image: postgres:14.1
    container_name: fifa-local-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=grzes
      - POSTGRES_PASSWORD=grzes
      - POSTGRES_DB=fifa_local_db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
volumes:
  postgres_data:
  pgadmin-data: