# Generated by Django 4.0.4 on 2022-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0004_alter_group_id_alter_profile_id_alter_team_id'),
        ('fifa_draft', '0034_alter_group_draft_order_and_more'),
    ]

    operations = [
    ]
