# Generated by Django 4.0.4 on 2022-07-02 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('password', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number_of_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)])),
                ('draft_order_choice', models.CharField(choices=[('Serpentine', 'Serpentine'), ('Fixed', 'Fixed')], default='Serpentine', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('draft_order', models.CharField(blank=True, max_length=200, null=True)),
                ('group_players', models.ManyToManyField(blank=True, related_name='group_players', to='players.player')),
                ('members', models.ManyToManyField(blank=True, default='users.Profile', related_name='members', to='users.profile')),
                ('owner', models.ForeignKey(db_constraint=False, default='users.Profile', on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('picking_person', models.ManyToManyField(blank=True, default='users.Profile', related_name='picking_person', to='users.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_password', models.CharField(max_length=50)),
                ('max_players', models.PositiveIntegerField(default=14)),
                ('formation', models.CharField(choices=[('4–4–2', '4–4–2'), ('4–3–3', '4–3–3'), ('4–1–2-1-2', '4–1–2-1-2'), ('4–4–1–1', '4–4–1–1'), ('4–3–2–1', '4–3–2–1'), ('4-2-3-1', '4-2-3-1'), ('3–4–3', '3–4–3'), ('5–3–2', '5–3–2')], default=('4–3–3', '4–3–3'), max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('belongs_group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fifa_draft.group')),
                ('owner', models.ForeignKey(default='users.Profile', on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('pending_player', models.ManyToManyField(blank=True, related_name='pending_player', to='players.player')),
                ('team_players', models.ManyToManyField(blank=True, related_name='team_players', to='players.player')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='fifa_draft.team'),
        ),
    ]
