# Generated by Django 4.0.4 on 2022-05-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='group',
            new_name='belongs_group',
        ),
    ]
