# Generated by Django 4.0.4 on 2022-07-01 16:07

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('fifa_draft', '0001_initial'),
        ('players', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(default=users.models.Profile, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='team',
            name='pending_player',
            field=models.ManyToManyField(blank=True, related_name='pending_player', to='players.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_players',
            field=models.ManyToManyField(blank=True, related_name='team_players', to='players.player'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_players',
            field=models.ManyToManyField(blank=True, related_name='group_players', to='players.player'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=users.models.Profile, related_name='members', to='users.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(db_constraint=False, default=users.models.Profile, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='picking_person',
            field=models.ManyToManyField(blank=True, default=users.models.Profile, related_name='picking_person', to='users.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='fifa_draft.team'),
        ),
    ]
