# Generated by Django 4.0.4 on 2022-05-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0002_alter_group_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teams',
        ),
    ]
