# Generated by Django 4.0.4 on 2022-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fifa_draft", "0002_remove_group_profiles_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="profiles_order",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
