# Generated by Django 4.0.4 on 2022-05-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0002_alter_group_owner_alter_team_belongs_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
