# Generated by Django 4.1 on 2022-08-23 17:17

from django.db import migrations, models
import fifa_draft.models


class Migration(migrations.Migration):

    dependencies = [
        ("fifa_draft", "0002_group_picking_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="group_images/",
                validators=[fifa_draft.models.Group.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_images/",
                validators=[fifa_draft.models.Team.validate_image],
            ),
        ),
    ]
