# Generated by Django 4.0.4 on 2022-05-04 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0002_remove_profile_bio_remove_profile_social_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('password', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='members', to='fifa_draft.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa_draft.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
