# Generated by Django 4.0.4 on 2022-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fifa_draft", "0002_group_teams_profile_draft_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
