# Generated by Django 4.0.4 on 2022-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fifa_draft", "0003_alter_group_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                default="group_images/default.jpg",
                null=True,
                upload_to="group_images/",
            ),
        ),
    ]
