# Generated by Django 4.0.4 on 2022-05-06 12:17

from django.db import migrations, models
import fifa_draft.models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0003_remove_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=fifa_draft.models.Profile, related_name='members', to='fifa_draft.profile'),
        ),
    ]
