# Generated by Django 4.0.4 on 2022-05-04 16:49

from django.db import migrations, models
import django.db.models.deletion
import fifa_draft.models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0004_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='number_of_players',
            field=models.IntegerField(default=18, max_length=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=fifa_draft.models.Profile, on_delete=django.db.models.deletion.CASCADE, to='fifa_draft.profile'),
        ),
    ]
