# Generated by Django 4.0.4 on 2022-05-30 14:07

import django.core.validators
from django.db import migrations, models
import fifa_draft.models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0004_alter_group_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofifa_id', models.IntegerField(default=False, verbose_name='sofifa_id')),
                ('player_url', models.CharField(default=False, max_length=150, verbose_name='player_url')),
                ('short_name', models.CharField(default=False, max_length=50, verbose_name='short_name')),
                ('player_positions', models.CharField(default=False, max_length=15, null=True, verbose_name='player_positions')),
                ('overall', models.IntegerField(null=True, verbose_name='overall')),
                ('age', models.IntegerField(null=True, verbose_name='age')),
                ('height_cm', models.IntegerField(null=True, verbose_name='height_cm')),
                ('weight_kg', models.IntegerField(null=True, verbose_name='weight_kg')),
                ('club_name', models.CharField(default=False, max_length=50, null=True, verbose_name='club_name')),
                ('preferred_foot', models.CharField(default=False, max_length=6, null=True, verbose_name='preferred_foot')),
                ('weak_foot', models.IntegerField(null=True, verbose_name='weak_foot')),
                ('skill_moves', models.IntegerField(null=True, verbose_name='skill_moves')),
                ('work_rate', models.CharField(default=False, max_length=50, null=True, verbose_name='work_rate')),
                ('pace', models.IntegerField(null=True, verbose_name='pace')),
                ('shooting', models.IntegerField(null=True, verbose_name='shooting')),
                ('passing', models.IntegerField(null=True, verbose_name='passing')),
                ('dribbling', models.IntegerField(null=True, verbose_name='dribbling')),
                ('defending', models.IntegerField(null=True, verbose_name='defending')),
                ('physic', models.IntegerField(null=True, verbose_name='physic')),
                ('player_face_url', models.CharField(default=False, max_length=200, null=True, verbose_name='player_face_url')),
                ('club_logo_url', models.CharField(default=False, max_length=200, null=True, verbose_name='club_logo_url')),
                ('nation_flag_url', models.CharField(default=False, max_length=200, null=True, verbose_name='nation_flag_url')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='draft_order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='picking_person',
            field=models.ManyToManyField(blank=True, default=fifa_draft.models.Profile, related_name='picking_person', to='fifa_draft.profile'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='formation',
            field=models.CharField(choices=[('4–4–2', '4–4–2'), ('4–3–3', '4–3–3'), ('4–1–2-1-2', '4–1–2-1-2'), ('4–4–1–1', '4–4–1–1'), ('4–3–2–1', '4–3–2–1'), ('4-2-3-1', '4-2-3-1'), ('3–4–3', '3–4–3'), ('5–3–2', '5–3–2')], default=('4–3–3', '4–3–3'), max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_of_players',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='group_players',
            field=models.ManyToManyField(blank=True, related_name='group_players', to='fifa_draft.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_players',
            field=models.ManyToManyField(blank=True, related_name='team_players', to='fifa_draft.player'),
        ),
    ]
