# Generated by Django 4.0.4 on 2022-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0005_alter_group_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='draft_teams',
            field=models.ManyToManyField(blank=True, related_name='draft_teams', to='fifa_draft.team'),
        ),
    ]
