# Generated by Django 4.0.4 on 2022-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0006_alter_team_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='formation',
            field=models.CharField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], max_length=10),
        ),
    ]
