# Generated by Django 4.0.4 on 2022-05-04 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0008_alter_group_number_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_players',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
