# Generated by Django 4.0.4 on 2022-05-04 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0009_alter_group_number_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_players',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
