# Generated by Django 4.0.4 on 2022-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0010_alter_group_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='draft_order_choices',
            field=models.CharField(choices=[('Serpentine', 'Serpentine'), ('Fixed', 'Fixed')], default='Serpentine', max_length=10),
        ),
    ]
