# Generated by Django 4.0.4 on 2022-05-05 12:10

from django.db import migrations, models
import django.db.models.deletion
import fifa_draft.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0012_rename_draft_order_choices_group_draft_order_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_password', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa_draft.group')),
                ('owner', models.ForeignKey(default=fifa_draft.models.Profile, on_delete=django.db.models.deletion.CASCADE, to='fifa_draft.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
