# Generated by Django 4.0.4 on 2022-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0013_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
