# Generated by Django 4.0.4 on 2022-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0015_remove_team_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
