# Generated by Django 4.0.4 on 2022-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fifa_draft", "0015_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="group_images/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
    ]
