# Generated by Django 4.0.4 on 2022-05-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0002_rename_group_team_belongs_group'),
        ('fifa_draft', '0016_team_max_players'),
    ]

    operations = [
    ]
