# Generated by Django 4.0.4 on 2022-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0018_alter_team_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='formation',
            field=models.CharField(choices=[('4–4–2', '4–4–2'), ('4–3–3', '4–3–3'), ('4–1–2-1-2', '4–1–2-1-2'), ('4–4–1–1', '4–4–1–1'), ('4–3–2–1', '4–3–2–1'), ('4-2-3-1', '4-2-3-1'), ('3–4–3', '3–4–3'), ('5–3–2', '5–3–2')], max_length=10),
        ),
    ]
