# Generated by Django 4.0.4 on 2022-05-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0020_alter_team_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofifa_id', models.IntegerField(verbose_name='sofifa_id')),
                ('player_url', models.CharField(max_length=50, verbose_name='player_url')),
                ('short_name', models.CharField(max_length=50, verbose_name='short_name')),
                ('player_positions', models.CharField(max_length=15, verbose_name='player_positions')),
                ('overall', models.IntegerField(verbose_name='overall')),
                ('age', models.IntegerField(verbose_name='age')),
                ('height_cm', models.IntegerField(verbose_name='height_cm')),
                ('weight_kg', models.IntegerField(verbose_name='weight_kg')),
                ('club_name', models.CharField(max_length=50, verbose_name='club_name')),
                ('preferred_foot', models.CharField(max_length=6, verbose_name='preferred_foot')),
                ('weak_foot', models.IntegerField(verbose_name='weak_foot')),
                ('skill_moves', models.IntegerField(verbose_name='skill_moves')),
                ('work_rate', models.CharField(max_length=50, verbose_name='work_rate')),
                ('pace', models.IntegerField(verbose_name='pace')),
                ('shooting', models.IntegerField(verbose_name='shooting')),
                ('passing', models.IntegerField(verbose_name='passing')),
                ('dribbling', models.IntegerField(verbose_name='dribbling')),
                ('defending', models.IntegerField(verbose_name='defending')),
                ('physic', models.IntegerField(verbose_name='physic')),
                ('player_face_url', models.CharField(max_length=200, verbose_name='player_face_url')),
                ('club_logo_url', models.CharField(max_length=200, verbose_name='club_logo_url')),
                ('nation_flag_url', models.CharField(max_length=200, verbose_name='nation_flag_url')),
            ],
        ),
    ]
