# Generated by Django 4.0.4 on 2022-05-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0021_playermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerModel',
            new_name='Player',
        ),
    ]
