# Generated by Django 4.0.4 on 2022-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0022_rename_playermodel_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='defending',
            field=models.IntegerField(null=True, verbose_name='defending'),
        ),
        migrations.AlterField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(null=True, verbose_name='dribbling'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pace',
            field=models.IntegerField(null=True, verbose_name='pace'),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.IntegerField(null=True, verbose_name='passing'),
        ),
        migrations.AlterField(
            model_name='player',
            name='physic',
            field=models.IntegerField(null=True, verbose_name='physic'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shooting',
            field=models.IntegerField(null=True, verbose_name='shooting'),
        ),
    ]
