# Generated by Django 4.0.4 on 2022-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0023_alter_player_defending_alter_player_dribbling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_logo_url',
            field=models.CharField(max_length=200, null=True, verbose_name='club_logo_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_name',
            field=models.CharField(max_length=50, null=True, verbose_name='club_name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height_cm',
            field=models.IntegerField(null=True, verbose_name='height_cm'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nation_flag_url',
            field=models.CharField(max_length=200, null=True, verbose_name='nation_flag_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='overall',
            field=models.IntegerField(null=True, verbose_name='overall'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_face_url',
            field=models.CharField(max_length=200, null=True, verbose_name='player_face_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_positions',
            field=models.CharField(max_length=15, null=True, verbose_name='player_positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_url',
            field=models.CharField(max_length=50, null=True, verbose_name='player_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(max_length=6, null=True, verbose_name='preferred_foot'),
        ),
        migrations.AlterField(
            model_name='player',
            name='short_name',
            field=models.CharField(max_length=50, null=True, verbose_name='short_name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_moves',
            field=models.IntegerField(null=True, verbose_name='skill_moves'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sofifa_id',
            field=models.IntegerField(null=True, verbose_name='sofifa_id'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weak_foot',
            field=models.IntegerField(null=True, verbose_name='weak_foot'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_kg',
            field=models.IntegerField(null=True, verbose_name='weight_kg'),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_rate',
            field=models.CharField(max_length=50, null=True, verbose_name='work_rate'),
        ),
    ]
