# Generated by Django 4.0.4 on 2022-05-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0024_alter_player_age_alter_player_club_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_logo_url',
            field=models.CharField(default=False, max_length=200, null=True, verbose_name='club_logo_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_name',
            field=models.CharField(default=False, max_length=50, null=True, verbose_name='club_name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nation_flag_url',
            field=models.CharField(default=False, max_length=200, null=True, verbose_name='nation_flag_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_face_url',
            field=models.CharField(default=False, max_length=200, null=True, verbose_name='player_face_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_positions',
            field=models.CharField(default=False, max_length=15, null=True, verbose_name='player_positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_url',
            field=models.CharField(default=False, max_length=150, verbose_name='player_url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(default=False, max_length=6, null=True, verbose_name='preferred_foot'),
        ),
        migrations.AlterField(
            model_name='player',
            name='short_name',
            field=models.CharField(default=False, max_length=50, verbose_name='short_name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sofifa_id',
            field=models.IntegerField(default=False, verbose_name='sofifa_id'),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_rate',
            field=models.CharField(default=False, max_length=50, null=True, verbose_name='work_rate'),
        ),
    ]
