# Generated by Django 4.0.4 on 2022-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0026_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='player', to='fifa_draft.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_players',
            field=models.ManyToManyField(blank=True, related_name='team_players', to='fifa_draft.player'),
        ),
    ]
