# Generated by Django 4.0.4 on 2022-05-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0027_group_players_team_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='players',
        ),
    ]
