# Generated by Django 4.0.4 on 2022-05-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0028_remove_group_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_players',
            field=models.ManyToManyField(blank=True, related_name='group_players', to='fifa_draft.player'),
        ),
    ]
