# Generated by Django 4.0.4 on 2022-05-24 16:54

from django.db import migrations, models
import fifa_draft.models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0029_group_group_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='picking_person',
            field=models.ManyToManyField(blank=True, default=fifa_draft.models.Profile, related_name='picking_person', to='fifa_draft.profile'),
        ),
    ]
