# Generated by Django 4.0.4 on 2022-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0031_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='draft_order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
