# Generated by Django 4.0.4 on 2022-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_draft', '0032_group_draft_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='draft_order',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
